# Generated by Django 4.0.3 on 2022-05-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0006_word_tagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField()),
                ('total', models.IntegerField()),
                ('percent', models.FloatField()),
                ('specific', models.BooleanField()),
                ('tags', models.ManyToManyField(blank=True, null=True, to='spell.tag')),
            ],
        ),
    ]
