# Generated by Django 4.0.3 on 2022-05-02 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='finished',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
