# Generated by Django 4.0.3 on 2022-06-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0015_word_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='definition',
            new_name='definition1',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='origin',
            new_name='origin1',
        ),
        migrations.AddField(
            model_name='word',
            name='definition2',
            field=models.TextField(default='cool', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='definition3',
            field=models.TextField(default='cool', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='origin2',
            field=models.TextField(default='cool', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='origin3',
            field=models.TextField(default='cool', max_length=600),
            preserve_default=False,
        ),
    ]
