# Generated by Django 4.0.3 on 2022-07-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0018_root_definition_root_origin_root_pp'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='locked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='subscribed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
