# Generated by Django 4.0.3 on 2022-07-27 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0022_rename_tags_report_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('identification', models.TextField(max_length=600)),
                ('word', models.TextField(max_length=100)),
                ('attempt', models.TextField()),
                ('result', models.TextField(max_length=10)),
                ('time', models.TextField(max_length=600)),
                ('iid', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spell.account'),
        ),
    ]
