# Generated by Django 4.0.3 on 2022-04-12 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0002_word_definition_word_origin_word_pronounce_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Set',
        ),
    ]
