# Generated by Django 4.0.3 on 2022-07-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0019_account_locked_account_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='words',
        ),
        migrations.AlterField(
            model_name='word',
            name='roots',
            field=models.ManyToManyField(blank=True, to='spell.root'),
        ),
        migrations.AlterField(
            model_name='word',
            name='tags',
            field=models.ManyToManyField(blank=True, to='spell.tag'),
        ),
    ]
