# Generated by Django 4.0.3 on 2022-07-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0020_remove_tag_words_alter_word_roots_alter_word_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='rooted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
