# Generated by Django 4.0.3 on 2022-07-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0027_account_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='customer_id',
            field=models.TextField(default='s', max_length=300),
            preserve_default=False,
        ),
    ]
