# Generated by Django 4.0.3 on 2022-08-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0031_account_changenotifs_account_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='children',
            field=models.ManyToManyField(blank=True, to='spell.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
