# Generated by Django 4.0.3 on 2022-04-06 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='definition',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='origin',
            field=models.TextField(default='', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='pronounce',
            field=models.TextField(default='', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='speech',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.TextField(max_length=100),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref', to='spell.word')),
            ],
        ),
    ]
