# Generated by Django 4.0.3 on 2022-04-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0005_alter_tag_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='tagged',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
