# Generated by Django 4.0.3 on 2022-05-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0010_alter_report_iid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='tags',
        ),
        migrations.AddField(
            model_name='report',
            name='tags',
            field=models.TextField(default='cool', max_length=100),
            preserve_default=False,
        ),
    ]
