# Generated by Django 4.0.3 on 2022-07-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0016_rename_definition_word_definition1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='roots',
            field=models.ManyToManyField(blank=True, null=True, to='spell.root'),
        ),
    ]
