# Generated by Django 4.0.3 on 2022-07-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0017_root_word_roots'),
    ]

    operations = [
        migrations.AddField(
            model_name='root',
            name='definition',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='root',
            name='origin',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='root',
            name='pp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
