# Generated by Django 4.0.3 on 2022-07-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0021_word_rooted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='tags',
            new_name='used',
        ),
    ]
