# Generated by Django 4.0.3 on 2022-07-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0024_rename_reportdetails_reportdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='trial_days_left',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
