# Generated by Django 4.0.3 on 2022-07-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0026_rename_trial_days_left_account_daysleft'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='trigger',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
