# Generated by Django 4.0.3 on 2022-08-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0030_emailvalidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='changenotifs',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='newsletter',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
