# Generated by Django 4.0.3 on 2022-08-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0034_confirmreq_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='parents',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
