# Generated by Django 4.0.3 on 2022-08-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0036_alter_account_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='spelling',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
