# Generated by Django 4.0.3 on 2022-08-25 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0037_report_spelling'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabReportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('identification', models.TextField(max_length=600)),
                ('word', models.TextField(max_length=100)),
                ('answer', models.TextField(max_length=1000)),
                ('attempt', models.TextField(max_length=1000)),
                ('result', models.TextField(max_length=10)),
                ('time', models.TextField(max_length=600)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spell.report')),
            ],
        ),
    ]
