# Generated by Django 4.0.3 on 2022-08-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0038_vocabreportdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabreportdetail',
            name='word',
        ),
        migrations.AddField(
            model_name='vocabreportdetail',
            name='question',
            field=models.TextField(default='Yay', max_length=1100),
            preserve_default=False,
        ),
    ]
