# Generated by Django 4.0.3 on 2022-08-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0039_remove_vocabreportdetail_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='repsub',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
