# Generated by Django 4.0.3 on 2022-08-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0040_account_repsub'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
