# Generated by Django 4.0.3 on 2022-08-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0041_tag_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='parent',
            field=models.IntegerField(null=True),
        ),
    ]
