# Generated by Django 4.0.3 on 2022-09-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0042_alter_tag_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='parent',
        ),
    ]
