# Generated by Django 4.0.3 on 2022-09-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0043_remove_tag_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='repsub',
        ),
    ]
