# Generated by Django 4.0.3 on 2022-09-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0044_remove_account_repsub'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='repsub',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
