# Generated by Django 4.0.3 on 2022-09-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0047_alter_tag_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='haschild',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
