# Generated by Django 4.0.3 on 2022-09-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0048_account_haschild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='haschild',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
