# Generated by Django 4.0.3 on 2022-12-29 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0049_alter_account_haschild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='daysleft',
        ),
        migrations.RemoveField(
            model_name='account',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='account',
            name='subscribed',
        ),
    ]
