# Generated by Django 4.0.3 on 2023-01-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0050_remove_account_customer_id_remove_account_daysleft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contactid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
