# Generated by Django 4.0.3 on 2023-01-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0053_account_contactid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='haschild',
        ),
    ]
