# Generated by Django 4.0.3 on 2023-01-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0054_remove_account_haschild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmreq',
            name='email',
        ),
        migrations.RemoveField(
            model_name='confirmreq',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='confirmreq',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='confirmreq',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='confirmreq',
            name='password',
        ),
        migrations.RemoveField(
            model_name='confirmreq',
            name='username',
        ),
    ]
