# Generated by Django 4.0.3 on 2023-01-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0055_remove_confirmreq_email_remove_confirmreq_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmreq',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spell.account'),
            preserve_default=False,
        ),
    ]
