# Generated by Django 4.1.6 on 2023-06-15 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0056_confirmreq_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_count', models.IntegerField()),
                ('acc_count', models.IntegerField()),
                ('correct', models.IntegerField()),
                ('progress', models.IntegerField()),
                ('words', models.TextField()),
                ('speech', models.TextField()),
                ('origin', models.TextField()),
                ('definition', models.TextField()),
                ('prons', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spell.report')),
            ],
        ),
    ]
