# Generated by Django 4.1.6 on 2023-06-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0058_reportdetail_finished_vocabreportdetail_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdetail',
            name='finished',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vocabreportdetail',
            name='finished',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
