# Generated by Django 4.1.6 on 2023-06-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0059_alter_reportdetail_finished_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdetail',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='vocabreportdetail',
            name='finished',
        ),
    ]
