# Generated by Django 4.1.6 on 2023-06-23 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0062_alter_reportdetail_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedactivity',
            name='attempts',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedactivity',
            name='ids_used',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedactivity',
            name='order',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedactivity',
            name='times',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spell.account'),
        ),
    ]
