# Generated by Django 4.1.6 on 2023-06-23 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0063_savedactivity_attempts_savedactivity_ids_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdetail',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='vocabreportdetail',
            name='finished',
        ),
    ]
