# Generated by Django 4.1.6 on 2023-06-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0065_reportdetail_finished_vocabreportdetail_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedactivity',
            name='total',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
