# Generated by Django 4.1.6 on 2023-06-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0066_savedactivity_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedactivity',
            name='correct_array',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
