# Generated by Django 4.1.6 on 2023-06-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0067_savedactivity_correct_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedactivity',
            name='final_roots',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedactivity',
            name='final_tags',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
